# Generated by Django 5.2 on 2025-04-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.IntegerField(unique=True)),
                ('symbol', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('atomic_weight', models.FloatField()),
                ('group', models.IntegerField()),
                ('period', models.IntegerField()),
            ],
        ),
    ]
