# Generated by Django 5.2 on 2025-04-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tableau_Periodique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='atomic_radius',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='element',
            name='electronegativity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='element',
            name='melting_point',
            field=models.FloatField(),
        ),
    ]
