# Generated by Django 5.2 on 2025-04-18 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tableau_Periodique', '0002_alter_element_atomic_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='masse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='element',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='position_col',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='position_row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
