# Generated by Django 5.2 on 2025-04-18 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tableau_Periodique', '0003_alter_element_masse_alter_element_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='electronegativity',
        ),
        migrations.RemoveField(
            model_name='element',
            name='melting_point',
        ),
    ]
