# Generated by Django 5.2 on 2025-04-18 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tableau_Periodique', '0004_remove_element_electronegativity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='atomic_radius',
        ),
    ]
